DROP TABLE IF EXISTS genres, ratings_MPA, films, users, film_like, film_genre, friends CASCADE;

CREATE TABLE IF NOT EXISTS genres (
     id INTEGER PRIMARY KEY,
     name varchar
    );

CREATE TABLE IF NOT EXISTS ratings_MPA (
     id INTEGER PRIMARY KEY,
     description varchar
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    description varchar,
    release_date TIMESTAMP,
    duration INTEGER,
    rating_MPA_Id INTEGER REFERENCES ratings_MPA (id)
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar,
    login varchar,
    name varchar,
    birthdate DATE
);

CREATE TABLE IF NOT EXISTS film_like (
    film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS film_genre (
    genre_id INTEGER REFERENCES genres (id) ON DELETE CASCADE,
    film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
    PRIMARY KEY (genre_id, film_id)
);

CREATE TABLE IF NOT EXISTS friends (
    initiator_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    target_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    confirm BOOLEAN,
    PRIMARY KEY (initiator_id, target_id)
);